# Generated by Django 4.0.3 on 2022-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_email', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
