# Generated by Django 4.0.3 on 2022-05-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('l_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('l_no', models.IntegerField(max_length=2, null=True)),
                ('block_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.block')),
            ],
        ),
    ]
