# Generated by Django 4.0.3 on 2022-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='comp_no',
            field=models.IntegerField(null=True),
        ),
    ]
