# Generated by Django 4.0.3 on 2022-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('bl_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bl_name', models.CharField(max_length=2, null=True, unique=True)),
            ],
        ),
    ]
