# Generated by Django 4.0.3 on 2022-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_computer_comp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='c_status',
            field=models.IntegerField(null=True),
        ),
    ]
