# Generated by Django 4.0.3 on 2022-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='comp_n',
            new_name='comp_id',
        ),
    ]
